name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installiere Abhängigkeiten
        run: npm install

      - name: Linter ausführen
        run: npm run lint

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installiere Abhängigkeiten
        run: npm install

      - name: Führe Tests aus
        run: npm test

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installiere Abhängigkeiten
        run: npm install

      - name: Simuliere Deployment
        run: echo "Deployment simuliert! Deine App ist bereit für die Produktion."
